"""Global configuration constants for kuroko-linkedin-agent."""

MAX_SCRAPE_REQUESTS_PER_DOMAIN = 20
SCRAPE_DELAY_MIN = 2.5
SCRAPE_DELAY_MAX = 5.0
MAX_ARTICLE_WORDS = 500
MAX_TOKENS_CLAUDE = 1500
POST_MIN_WORDS = 150
POST_MAX_WORDS = 300
POST_MAX_HASHTAGS = 4
QUALITY_SCORE_THRESHOLD = 7
MAX_GENERATION_RETRIES = 2
IMAGE_EVERY_N_POSTS = 3
DEDUP_DAYS = 14
POSTING_DAYS = [1, 3]  # Tuesday=1, Thursday=3
POSTING_HOURS = [(8, 10), (12, 13)]
